import * as Yup from "yup";
const regExp = /\b\d{4}\b/;

export const questionsSchema = Yup.object().shape({
  username: Yup.string().required("نام کاربری الزامیست."),
  idNumber: Yup.string().required("تاریخ تولد الزامیست.").matches(regExp, {
    message: "تاریخ وارد شده صحیح نمی باشد.",
    excludeEmptyString: true,
  }),
  q1: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q2: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q3: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q4: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q5: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q6: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q7: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q8: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q9: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q10: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q11: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q12: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q13: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q14: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q15: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q16: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q17: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q18: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q19: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q20: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q21: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q22: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q23: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q24: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
  q25: Yup.string().required("لطفا یک گزینه را انتخاب کنید."),
});
